import Head from 'next/head';
import Homebanner from '@/components/Homebanner';
import Aboutus from '@/components/Aboutus';
import Packages from '@/components/Packages';
import Offer from '@/components/Offer';
import Form from '@/components/Form';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Journey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/journey_title_icon.png" />
      </Head>
      <Homebanner />
      <Aboutus />
      <Packages />
      <Offer />
      <Form />
      <Footer />
    </>
  )
}
